"""describe your change

Revision ID: 444f42395f66
Revises: 
Create Date: 2026-02-21 16:37:05.730643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444f42395f66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
