"""add title column in conversation table

Revision ID: 9b8869a5826b
Revises: 444f42395f66
Create Date: 2026-02-27 07:00:15.728334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b8869a5826b'
down_revision = '444f42395f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('langchain_pg_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cmetadata_gin'), postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')

    op.drop_table('langchain_pg_embedding')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('document_chunks_embedding_hnsw_idx'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'}, postgresql_using='hnsw')
        batch_op.drop_index(batch_op.f('document_chunks_embedding_idx'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('langchain_pg_collection', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('cmetadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('langchain_pg_collection_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('langchain_pg_collection', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('langchain_pg_collection_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('cmetadata',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('document_chunks_embedding_idx'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
        batch_op.create_index(batch_op.f('document_chunks_embedding_hnsw_idx'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'}, postgresql_using='hnsw')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('title')

    op.create_table('langchain_pg_embedding',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_embedding_pkey'))
    )
    with op.batch_alter_table('langchain_pg_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cmetadata_gin'), ['cmetadata'], unique=False, postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')

    # ### end Alembic commands ###
